config/routes.rb
AMSS::Application.routes.draw do

  post "wizard/done" => 'wizard#done'

  post "wizard/add_exams" => 'wizard#addExams'

  post "wizard/add_pos" => 'wizard#addPos'

  post "wizard/add_dept" => 'wizard#addDept'

  post "wizard/add_admin" => 'wizard#addAdmin'

  get "wizard" => 'wizard#index', :as => :wizard

  get 'applicants/applicant_summary/:id' => 'applicants#applicant_summary', :as => 'applicant/view_summary'

  get 'admins/log/:id' => 'admins#show_logs', :as=>'admin/logs'

  post 'schedules/interviewer_grade_decision/:id' => 'schedules#interviewer_grade_decision', :as => 'interviewer/grade_decision'

  get 'schedules/getSched/:filter' => 'schedules#getSched'

  get 'schedules/per/interviewer' => 'schedules#per_interviewer', :as => 'interviewer_schedules'

  get 'schedules/per/applicant' => 'schedules#per_applicant', :as => 'applicant_schedules'

  get 'schedules/getEvent' => 'schedules#getEvent'

  put 'update_grade/:id/exam/:exam_id' => 'applicants#update_grade', :as => :update_grade

  post 'assign_grade/:id' => 'applicants#assign_grade', :as => :assign_grade

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'applicants/matched_db_applicants' => 'applicants#matched_db_applicants', :as => 'applicants/verify'
  get 'applicants/matched_db_applicants/:id' => 'applicants#matched_db_applicants', :as => 'applicants/renew'

  resources :admins

  resources :schools

  resources :departments

  get 'interviewers/show_all' => 'interviewers#show_all'

  post 'interviewers/show_all' => 'interviewers#show_all'

  get 'schedules/new/:id' => 'schedules#new', :as => 'schedules/new'

  get 'positions/:id/exams/unassign/:exam_id' => 'positions#unassign', :as => :unassign

  get 'positions/:id/exams/assign/:exam_id' => 'positions#assign', :as => :assign

  controller :applicants do
    con = 'applicants/'
    get con+'show_all' => :show_all
    post con+'show_all' => :show_all, :as => 'show_all'
    post con+':id' => :show
    get 'search_applicant' => :search_applicant
    get con+'header_search' => :header_search
    get 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'
    post 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'

  	get con+'get_info' => :get_info
  	get con+'get_interviewer' => :get_interviewer
  end

  resources :schedules

  resources :grades

  resources :exams

  resources :interviewers

  resources :positions, :only =>[:index, :create, :update, :destroy, :show]

  resources :applicants

  root :to => "home#index", :as => "index"

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :exam
  belongs_to :applicant

  validates :score, :numericality => { only_integer: true,
                             greater_than: 0, :allow_blank=> true}
  validates_uniqueness_of :exam_id, :scope=>:applicant_id

  validate :score_is_not_greater_than

  def score_is_not_greater_than
    exam = Exam.find(exam_id)
    if !score.nil?
      if score.to_i > exam.total_score
        errors.add(:score, "can't be greater than the total score")
      end
    end
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  # GET /grades
  # GET /grades.xml
  def index
    @grades = Grade.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @grades }
    end
  end

  # GET /grades/1
  # GET /grades/1.xml
  def show
    @grade = Grade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @grade }
    end
  end

  # GET /grades/new
  # GET /grades/new.xml
  def new
    @grade = Grade.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @grade }
    end
  end

  # GET /grades/1/edit
  def edit
    @grade = Grade.find(params[:id])
  end

  # POST /grades
  # POST /grades.xml
  def create
    @grade = Grade.new(params[:grade])

    respond_to do |format|
      if @grade.save
        format.html { redirect_to(@grade, :notice => 'Grade was successfully created.') }
        format.xml  { render :xml => @grade, :status => :created, :location => @grade }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @grade.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /grades/1
  # PUT /grades/1.xml
  def update
    @grade = Grade.find(params[:id])

    respond_to do |format|
      if @grade.update_attributes(params[:grade])
        format.html { redirect_to(@grade, :notice => 'Grade was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @grade.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.xml
  def destroy
    @grade = Grade.find(params[:id])
    @grade.destroy

    respond_to do |format|
      format.html { redirect_to(grades_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grade %><br />
    <%= f.text_field :grade %>
  </div>
  <div class="field">
    <%= f.label :exam_id %><br />
    <%= f.text_field :exam_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<h1>Listing grades</h1>

<table>
  <tr>
    <th>Grade</th>
    <th>Exam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grades.each do |grade| %>
  <tr>
    <td><%= grade.grade %></td>
    <td><%= grade.exam_id %></td>
    <td><%= link_to 'Show', grade %></td>
    <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
    <td><%= link_to 'Destroy', grade, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grade', new_grade_path %>

app/views/grades/new.html.erb
<h1>New grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Grade:</b>
  <%= @grade.grade %>
</p>

<p>
  <b>Exam:</b>
  <%= @grade.exam_id %>
</p>


<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>