config/routes.rb
AMSS::Application.routes.draw do

  post "wizard/done" => 'wizard#done'

  post "wizard/add_exams" => 'wizard#addExams'

  post "wizard/add_pos" => 'wizard#addPos'

  post "wizard/add_dept" => 'wizard#addDept'

  post "wizard/add_admin" => 'wizard#addAdmin'

  get "wizard" => 'wizard#index', :as => :wizard

  get 'applicants/applicant_summary/:id' => 'applicants#applicant_summary', :as => 'applicant/view_summary'

  get 'admins/log/:id' => 'admins#show_logs', :as=>'admin/logs'

  post 'schedules/interviewer_grade_decision/:id' => 'schedules#interviewer_grade_decision', :as => 'interviewer/grade_decision'

  get 'schedules/getSched/:filter' => 'schedules#getSched'

  get 'schedules/per/interviewer' => 'schedules#per_interviewer', :as => 'interviewer_schedules'

  get 'schedules/per/applicant' => 'schedules#per_applicant', :as => 'applicant_schedules'

  get 'schedules/getEvent' => 'schedules#getEvent'

  put 'update_grade/:id/exam/:exam_id' => 'applicants#update_grade', :as => :update_grade

  post 'assign_grade/:id' => 'applicants#assign_grade', :as => :assign_grade

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'applicants/matched_db_applicants' => 'applicants#matched_db_applicants', :as => 'applicants/verify'
  get 'applicants/matched_db_applicants/:id' => 'applicants#matched_db_applicants', :as => 'applicants/renew'

  resources :admins

  resources :schools

  resources :departments

  get 'interviewers/show_all' => 'interviewers#show_all'

  post 'interviewers/show_all' => 'interviewers#show_all'

  get 'schedules/new/:id' => 'schedules#new', :as => 'schedules/new'

  get 'positions/:id/exams/unassign/:exam_id' => 'positions#unassign', :as => :unassign

  get 'positions/:id/exams/assign/:exam_id' => 'positions#assign', :as => :assign

  controller :applicants do
    con = 'applicants/'
    get con+'show_all' => :show_all
    post con+'show_all' => :show_all, :as => 'show_all'
    post con+':id' => :show
    get 'search_applicant' => :search_applicant
    get con+'header_search' => :header_search
    get 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'
    post 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'

  	get con+'get_info' => :get_info
  	get con+'get_interviewer' => :get_interviewer
  end

  resources :schedules

  resources :grades

  resources :exams

  resources :interviewers

  resources :positions, :only =>[:index, :create, :update, :destroy, :show]

  resources :applicants

  root :to => "home#index", :as => "index"

end

app/views/admins/_form.html.erb
 <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @admin, :html => {:multipart => true, :class=>"form-horizontal"} do |f| %>
 <div class="col-md-11 col-md-offset-1">
  <br />
    <div class="field col-md-3">
      <%= label_tag "Picture" %><br />
      <canvas id="myCanvas" class="thumbnail"></canvas>
      <input id="base64" type="hidden" value="" name="base64"/>
      <input id="imgName" type="hidden" value="" name="imgName"/>
      <input type='file' name = "admin[image]" accept="image/*"
      onchange="readURL(this);" id = "uploader" class="btn" />
    </div>
    <div class="col-md-5">
      <div class="field">
        <%= f.label :name, 'Username' %>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password, 'Password:'%>
        <%= f.password_field :password, :size=>40, :class => "form-control" %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, :size=>40, :class => "form-control" %>
      </div>
      <br />
      <div class="actions">
        <%= f.submit :class => "btn btn-success col-md-5 col-md-offset-1" %>
      </div>
    </div>
    <div class="col-md-12">
      <br />
        <%= link_to 'Back', admins_path, :class => "btn btn-default col-md-2" %>
    </div>
  </div>

<% end %>

<script type="text/javascript">

  $(window).load(function(){
    <% if @image_data != nil %>
      showPreview( "<%= @image_data %>" )
    <% elsif @admin.image_name.nil? %>
      showPreview( <%="'#{image_path('new_applicant.png')}'"%> )
    <% elsif !File.exists?("#{RAILS_ROOT}/public/images/#{@admin.image_name}") %>
      showPreview( <%="'#{image_path('404.jpg')}'"%> )
    <% else %>
      showPreview( <%="'#{image_path(@admin.image_name)}'"%> )
    <% end %>
  });

  function readURL(input) {

    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {

        var canvas = document.getElementById('myCanvas');
        var context = canvas.getContext('2d');
        var x = 0;
        var y = 0;
        var width = 500;
        var height = 500;
        var imageObj = new Image();

        $('#imgName').val($('#uploader').val());

        imageObj.onload = function() {
          context.drawImage(imageObj, x, y, width, height);
          $('#base64').val(canvas.toDataURL());
        };
          imageObj.src = e.target.result;
        }
    };
    reader.readAsDataURL(input.files[0]);
  }

  function showPreview(path){
    var img = new Image();
    var can = document.getElementById('myCanvas');
    var ctx = can.getContext('2d');
    $('#imgName').val(<%= "'#{@admin.image_name}'" %>);

    img.onload = function(){
      can.width = 500;
      can.height = 500;
      ctx.drawImage(img, 0, 0, can.width, can.height);
      $('#base64').val(can.toDataURL());
    }
    img.src = path;
  }
</script>

app/views/admins/edit.html.erb
<h1 class="page-header">Editing Administrator</h1>

<%= render 'form' %>

app/views/admins/index.html.erb
<h1 class="page-header">ADMINISTRATORS</h1>

<% if alert%>

  <div class="alert alert-danger alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h3> <%= alert %> </h3>
  </div>

<% end %>


<% if notice%>

  <div class="alert alert-success alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h3> <%= notice %> </h3>
  </div>

<% end %>


<div class="col-md-12">
<%= link_to 'New Admin', new_admin_path, :class => "btn btn-success col-md-2" %>
</div>
<div class="clearfix">&nbsp;</div>

<div class="container-fluid">
  <div class="row masonry">
  <% @admins.each do |admin| %>
    <div class="item">
      <div class="thumbnail">
        <% if File.exists?("#{RAILS_ROOT}/public/images/#{admin.image_name}") && !admin.image_name.nil? %>
          <%= image_tag admin.image_name, :width=>'100%', :height=>'100%',
         :alt=>admin.name,
         :title=> admin.name,
         :class => "thumbnail" %>
        <% else %>
          <%= image_tag('404.jpg', :width=>'100%', :height=>"100%", :class=>"thumbnail") %>
        <% end %>
        <div class="caption">
          <p style="font-size: 2em">
            <%=admin.name%>
          </p>

          <p class="text-center">
            <%= link_to 'Show', admin , :class=>"btn btn-primary"%>
            <%= link_to 'Edit', edit_admin_path(admin), :class=>"btn btn-warning" %>
            <%= link_to 'Remove', admin, :confirm => 'Are you sure?', :method => :delete, :class=>"btn btn-danger" %>
          </p>
          <span class="clearfix"></span>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/admins/new.html.erb
<h1 class="page-header">New Administrator</h1>

<%= render 'form' %>

app/views/admins/show.html.erb
<h1 class="page-header">Administrator Info</h1>
<p id="notice"><%= notice %></p>
<div class="col-md-9 jumbotron">
	<p>
	  <b>Username:</b>
	  <%= @admin.name %>
	</p>

	<p>
	  <b>Hashed password:</b>
	  <%= @admin.hashed_password %>
	</p>

	<p>
	  <b>Salt:</b>
	  <%= @admin.salt %>
	</p>
	<%= link_to 'Back', admins_path, :class => "btn btn-default" %>
	<%= link_to 'Edit', edit_admin_path(@admin), :class => "btn btn-danger" %>
</div>

app/views/admins/show_logs.html.erb
<h1 class="page-header">LOGS</h1>
<div class="col-md-2">
	<%=link_to "Back", index_path, :class=>"btn btn-success col-md-12" %>
</div>
<div class="col-md-12">
<br />
<div class="panel panel-success">
  <div class="panel-heading"><h4>Admin <%= @admin.name %></h4></div>
    <div class="panel-body">
			<table class="table table-default table-responsive table-bordered table-striped">
				<tr>
					<th>Date</th>
					<th>Log</th>
				</tr>
				<% @logs.each do |log| %>
					<tr>
						<td><%= log.created_at %></td>
						<td><%= log.log %></td>
					</tr>
				<% end %>
		  </table>
   </div>
</div>
</div>