config/routes.rb
AMSS::Application.routes.draw do

  post "wizard/done" => 'wizard#done'

  post "wizard/add_exams" => 'wizard#addExams'

  post "wizard/add_pos" => 'wizard#addPos'

  post "wizard/add_dept" => 'wizard#addDept'

  post "wizard/add_admin" => 'wizard#addAdmin'

  get "wizard" => 'wizard#index', :as => :wizard

  get 'applicants/applicant_summary/:id' => 'applicants#applicant_summary', :as => 'applicant/view_summary'

  get 'admins/log/:id' => 'admins#show_logs', :as=>'admin/logs'

  post 'schedules/interviewer_grade_decision/:id' => 'schedules#interviewer_grade_decision', :as => 'interviewer/grade_decision'

  get 'schedules/getSched/:filter' => 'schedules#getSched'

  get 'schedules/per/interviewer' => 'schedules#per_interviewer', :as => 'interviewer_schedules'

  get 'schedules/per/applicant' => 'schedules#per_applicant', :as => 'applicant_schedules'

  get 'schedules/getEvent' => 'schedules#getEvent'

  put 'update_grade/:id/exam/:exam_id' => 'applicants#update_grade', :as => :update_grade

  post 'assign_grade/:id' => 'applicants#assign_grade', :as => :assign_grade

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'applicants/matched_db_applicants' => 'applicants#matched_db_applicants', :as => 'applicants/verify'
  get 'applicants/matched_db_applicants/:id' => 'applicants#matched_db_applicants', :as => 'applicants/renew'

  resources :admins

  resources :schools

  resources :departments

  get 'interviewers/show_all' => 'interviewers#show_all'

  post 'interviewers/show_all' => 'interviewers#show_all'

  get 'schedules/new/:id' => 'schedules#new', :as => 'schedules/new'

  get 'positions/:id/exams/unassign/:exam_id' => 'positions#unassign', :as => :unassign

  get 'positions/:id/exams/assign/:exam_id' => 'positions#assign', :as => :assign

  controller :applicants do
    con = 'applicants/'
    get con+'show_all' => :show_all
    post con+'show_all' => :show_all, :as => 'show_all'
    post con+':id' => :show
    get 'search_applicant' => :search_applicant
    get con+'header_search' => :header_search
    get 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'
    post 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'

  	get con+'get_info' => :get_info
  	get con+'get_interviewer' => :get_interviewer
  end

  resources :schedules

  resources :grades

  resources :exams

  resources :interviewers

  resources :positions, :only =>[:index, :create, :update, :destroy, :show]

  resources :applicants

  root :to => "home#index", :as => "index"

end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
	attr_accessor :image
	
	has_and_belongs_to_many :applicants
	
	has_many :schedules
	
	belongs_to :department 
end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
  # GET /interviewers
  # GET /interviewers.xml
  def index
    @interviewers = Interviewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interviewers }
    end
  end

  # GET /interviewers/1
  # GET /interviewers/1.xml
  def show
    @interviewer = Interviewer.find(params[:id])

    now = DateTime.now

    @next_sched = @interviewer.schedules.where(["sched_start > ?", now]) #.find(:conditions=>["sched_start < ?", now])
    @prev_sched = @interviewer.schedules.where(["sched_start < ?", now]) #.find(:conditions=>["sched_start < ?", now])


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interviewer }
    end
  end

  # GET /interviewers/new
  # GET /interviewers/new.xml
  def new
    @interviewer = Interviewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interviewer }
    end
  end

  # GET /interviewers/1/edit
  def edit
    @interviewer = Interviewer.find(params[:id])
  end

  # POST /interviewers
  # POST /interviewers.xml
  def create
    @interviewer = Interviewer.new(params[:interviewer])
    
    @interviewer.department_id = params[:department_id]

    file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.png"
    @interviewer.image_name = "upload_images/interviewers/"+file_name

    respond_to do |format|
      if @interviewer.save
        upload_image(file_name, params[:base64])
        AdminLog.create(:admin_id=>session[:admin_id], :log=>"Created new interviewer -> "+@interviewer.id.to_s)
        format.html { redirect_to(@interviewer, :notice => 'Interviewer was successfully created.') }
        format.xml  { render :xml => @interviewer, :status => :created, :location => @interviewer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interviewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interviewers/1
  # PUT /interviewers/1.xml
  def update
    @interviewer = Interviewer.find(params[:id])
    @interviewer.department_id = params[:department_id]
    if !@interviewer.image_name.nil?
      file_name = @interviewer.image_name.split('/').last
    else
      file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.png"
    end
  
    respond_to do |format|
      if @interviewer.update_attributes(params[:interviewer])
        if @interviewer.image_name != params[:imgName]
          upload_image(file_name, params[:base64])
        end
        AdminLog.create(:admin_id=>session[:admin_id], :log=>"Updated a interviewer -> "+@interviewer.id.to_s)
        format.html { redirect_to(@interviewer, :notice => 'Interviewer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interviewer.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show_all
    @selected_filter = 0
    if params[:commit] == "FILTER"
      if params[:filter_by] == ""
        @interviewers = Interviewer.all
      else
        @selected_filter = params[:filter_by]
        @interviewers = Interviewer.find(:all, :conditions => ["department_id = ?", params[:filter_by]])
      end
    else
      @interviewers = Interviewer.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interviewers }
    end
  end

  # DELETE /interviewers/1
  # DELETE /interviewers/1.xml
  def destroy
    @interviewer = Interviewer.find(params[:id])
    if File.exists?("#{RAILS_ROOT}/public/images/#{@interviewer.image_name}")
      File.delete("#{RAILS_ROOT}/public/images/#{@interviewer.image_name}")
    end
    AdminLog.create(:admin_id=>session[:admin_id], :log=>"Removed a interviewer -> "+@interviewer.id.to_s)
    @interviewer.destroy

    respond_to do |format|
      format.html { redirect_to(interviewers_url) }
      format.xml  { head :ok }
    end
  end

  def upload_image(image, base64)
    require 'fileutils'
    data =  base64
    image_data = Base64.decode64(data['data:image/png;base64,'.length .. -1])
    who = 'interviewers'
    file_name = image
    file_path = File.join(Rails.root, 'public', 'images', 'upload_images', who, file_name)
    File.open(file_path, 'wb') do |f|
      f.write image_data
    end
  end

end

app/helpers/interviewers_helper.rb
module InterviewersHelper
end

app/views/interviewers/_form.html.erb
<% if @interviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interviewer.errors.count, "error") %> prohibited this interviewer from being saved:</h2>

      <ul>
      <% @interviewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
<%= form_for @interviewer, :html => {:multipart => true, :class=>"form-horizontal"} do |f| %>

  <div class="field col-md-3 text-center">
      <%= label_tag "Picture" %><br />
      <canvas id="myCanvas"></canvas>
      <input id="base64" type="hidden" value="" name="base64"/>
      <input id="imgName" type="hidden" value="" name="imgName"/>
      <input type='file', name = "interviewer[image]", accept="image/*",
      onchange="readURL(this);", id = "uploader"/>
  </div>

  <div class="col-md-6">
    <br/><br/>
    <div class="field form-group">
      <%= f.label "Full Name:", :class=>"control-label col-md-3"%>
      <div class="col-md-9">
      <%= f.text_field :name , :class => "form-control", :required=> true%>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label "Position Title:", :class=>"control-label col-md-3"%>
      <div class="col-md-9">
      <%= f.text_field :position_title, :class => "form-control", :required=> true %>
      </div>
    </div>

    <div class="field form-group">
      <%= f.label "Department Name:", :class=>"control-label col-md-3"%>
      <div class="col-md-9">
      <%= select_tag :department_id, options_for_select(Department.all.collect {|x| [x.department_name, x.id]},
      	:selected => @interviewer.department_id ),:include_blank => "Select one", :class => "form-control", :required=> true %>
      </div>
    </div>

    <div class="field">
    	<br />
      <%= f.submit :class => "btn btn-danger" %>
    </div>
  </div>
<% end %>
</div>
<script type="text/javascript">

  $(window).load(function(){
      <% if @interviewer.image_name.nil? %>
        showPreview( <%="'#{image_path('new_applicant.png')}'"%> )
      <% elsif !File.exists?("#{RAILS_ROOT}/public/images/#{@interviewer.image_name}") %>
        showPreview( <%="'#{image_path('404.jpg')}'"%> )
      <% else %>
      	showPreview( <%="'#{image_path(@interviewer.image_name)}'"%> )
      <% end %>
    });

  function readURL(input) {

    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {

        var canvas = document.getElementById('myCanvas');
        var context = canvas.getContext('2d');
        var x = 0;
        var y = 0;
        var width = 500;
        var height = 500;
        var imageObj = new Image();

        $('#imgName').val($('#uploader').val());

        imageObj.onload = function() {
          context.drawImage(imageObj, x, y, width, height);
          $('#base64').val(canvas.toDataURL());
        };
          imageObj.src = e.target.result;
        }
    };
    reader.readAsDataURL(input.files[0]);
  }

  function showPreview(path){
    var img = new Image();
    var can = document.getElementById('myCanvas');
    var ctx = can.getContext('2d');
    $('#imgName').val(<%= "'#{@interviewer.image_name}'" %>);

    img.onload = function(){
      can.width = 500;
      can.height = 500;
      ctx.drawImage(img, 0, 0, can.width, can.height);
      $('#base64').val(can.toDataURL());
    }
    img.src = path;
  }
</script>

app/views/interviewers/edit.html.erb
<h1>Editing interviewer</h1>
<div class="col-md-12">
<div class="col-md-12"><%= render 'form' %></div>
<div class="col-md-12"><%= link_to 'Back', interviewers_path, :class => "btn btn-default col-md-1" %></div>
</div>

app/views/interviewers/index.html.erb
<div class="page-header">
<%= link_to 'Add new Interviewer', new_interviewer_path %> | 
<%= link_to 'Show all Interviewers', interviewers_show_all_path %>
</div>

app/views/interviewers/new.html.erb
<h1 class="page-header">New interviewer</h1>

<%= render 'form' %>

app/views/interviewers/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">Interviewer's Information</h1>
<div class="row">
	<div class="col-md-6 col-xs-12">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-success ap_info">
					<div class="panel-heading">
						<% if File.exists?("#{RAILS_ROOT}/public/images/#{@interviewer.image_name}") %>
              <%= image_tag "#{@interviewer.image_name}" , :size => "200x200" , :class=>"img-circle" %>
            <% else %>
              <%= image_tag('404.jpg' , :size => "200x200") %>
            <% end %>
            &nbsp;
          </div>

          <h1 class="page-header text-right">
          	<%= @interviewer.name %>
          </h1>
          <div class="clearfix"></div>

          <div class="panel-body">
						<p>  <label>Position Title: </label><%= @interviewer.position_title %></p>
						<p>  <label>Department:</label>  <%= @interviewer.department.department_name %>   </p>
          </div>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-6 col-xs-12">

		<div class="col-md-12">
      <div class="row">
          <div class="panel panel-success">
            <div class="panel-heading">Next Schedules</div>
              <div class="panel-body table-responsive">
              	<% if @next_sched %>
              		<table class="table table-hover">
	              		<thead>
	              			<tr>
	              				<th>Date</th>
	              				<th>Time</th>
	              				<th>Applicant</th>
	              				<th></th>
	              				<th></th>
	              			</tr>
              			</thead>
	              		<tbody>
	              		<% @next_sched.each do |sched|%>
											<%applicant = sched.applicant%>
				              <% name = applicant.firstname + ' ';
				                unless applicant.middlename.blank?
				                      name += (applicant.middlename.first.upcase + '. ')
				                end
				              name += applicant.lastname %>

		              		<tr>
			              		<td><%= sched.sched_start.strftime('%B %d, %Y') %></td>
			              		<td><%= sched.sched_start.strftime('%H:%m %p') %> -
              							<%= sched.sched_end.strftime('%H:%m %p') %></td>
						            <td><%= name%></td>
						            <td><%= link_to 'Show', sched %></td>
						            <td><%= link_to 'Cancel', sched, :confirm => 'Are you sure?', :method => :delete %></td>
			              	</tr>
		            		<% end %>
		              	</tbody>
	              	</table>
              	<% else %>
              		No Next schedule
              	<% end %>
              </div>
          </div>
      </div>
    </div>

		<div class="col-md-12">
      <div class="row">
          <div class="panel panel-success">
            <div class="panel-heading">Previous Schedules</div>
              <div class="panel-body">
              	<% if @prev_sched %>
              		<table class="table table-hover">
	              		<thead>
	              			<tr>
	              				<th>Date</th>
	              				<th>Time</th>
	              				<th>Applicant</th>
	              				<th></th>
	              				<th></th>
	              			</tr>
              			</thead>
	              		<tbody>
	              		<% @prev_sched.each do |sched|%>
											<%applicant = sched.applicant%>
				              <% name = applicant.firstname + ' ';
				                unless applicant.middlename.blank?
				                      name += (applicant.middlename.first.upcase + '. ')
				                end
				              name += applicant.lastname %>

		              		<tr>
			              		<td><%= sched.sched_start.strftime('%B %d, %Y') %></td>
			              		<td><%= sched.sched_start.strftime('%H:%m %p') %> -
              							<%= sched.sched_end.strftime('%H:%m %p') %></td>
						            <td><%= name%></td>
						            <td><%= link_to 'Show', sched %></td>

						            <% if sched.grade.nil? %>
            						<td><%= link_to 'Cancel', sched, :confirm => 'Are you sure?', :method => :delete %></td>
          							<% else %>
            						<td><%= link_to get_interviewer_grade(sched), '#' %><br />Remarks: <%= sched.remarks %></td>
          							<% end %>
			              	</tr>
		            		<% end %>
		              	</tbody>
	              	</table>
	              <% else %>
	              	No previous Schedule
	              <% end %>
              </div>
          </div>
      </div>
		</div>
	</div>
</div>
<div class="col-md-12">
<%= link_to 'Edit', edit_interviewer_path(@interviewer), :class => "btn btn-success col-md-1" %>
<%= link_to 'Back', interviewers_show_all_path, :class => "btn btn-success col-md-1" %>
</div>

app/views/interviewers/show_all.html.erb
<h1 class="page-header">INTERVIEWERS</h1>

<%= form_tag interviewers_show_all_path do %>
<div class="col-md-12">
  <div class="col-md-4">
  <%= select_tag "filter_by", options_from_collection_for_select(Department.all, "id", "department_name", @selected_filter), :include_blank => "All", :class => "form-control" , :style => "font-weight:bold; font-size:15px"%>
  </div>
  <%= submit_tag "FILTER", :class => "btn btn-primary col-md-2" %>
  <%= link_to 'Back', interviewers_path, :class => "btn btn-default col-md-1 col-md-offset-5" %>
  </div>
<% end %>
<div class="clearfix"></div>
<br />
<% if !@interviewers.any? %>
  <blockquote><h3>There is no registered interviewer for this department.</h3></blockquote>
<% else %>
<table class="table table-hover table-responsive table-striped">
  <tr>
    <th>Picture</th>
    <th>Name</th>
    <th>Position</th>
    <th>Department</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviewers.each do |interviewer| %>
  <tr>
    <td><%= image_tag(interviewer.image_name, :size => "75x75", :class => "thumbnail") %></td>
    <td><%= interviewer.name %></td>
    <td><%= interviewer.position_title %></td>
    <td><%= interviewer.department.department_name %></td>
    <td><%= link_to 'Show', interviewer %></td>
    <td><%= link_to 'Edit', edit_interviewer_path(interviewer) %></td>
    <td><%= link_to 'Remove', interviewer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<% end %>