config/routes.rb
AMSS::Application.routes.draw do

  post "wizard/done" => 'wizard#done'

  post "wizard/add_exams" => 'wizard#addExams'

  post "wizard/add_pos" => 'wizard#addPos'

  post "wizard/add_dept" => 'wizard#addDept'

  post "wizard/add_admin" => 'wizard#addAdmin'

  get "wizard" => 'wizard#index', :as => :wizard

  get 'applicants/applicant_summary/:id' => 'applicants#applicant_summary', :as => 'applicant/view_summary'

  get 'admins/log/:id' => 'admins#show_logs', :as=>'admin/logs'

  post 'schedules/interviewer_grade_decision/:id' => 'schedules#interviewer_grade_decision', :as => 'interviewer/grade_decision'

  get 'schedules/getSched/:filter' => 'schedules#getSched'

  get 'schedules/per/interviewer' => 'schedules#per_interviewer', :as => 'interviewer_schedules'

  get 'schedules/per/applicant' => 'schedules#per_applicant', :as => 'applicant_schedules'

  get 'schedules/getEvent' => 'schedules#getEvent'

  put 'update_grade/:id/exam/:exam_id' => 'applicants#update_grade', :as => :update_grade

  post 'assign_grade/:id' => 'applicants#assign_grade', :as => :assign_grade

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'applicants/matched_db_applicants' => 'applicants#matched_db_applicants', :as => 'applicants/verify'
  get 'applicants/matched_db_applicants/:id' => 'applicants#matched_db_applicants', :as => 'applicants/renew'

  resources :admins

  resources :schools

  resources :departments

  get 'interviewers/show_all' => 'interviewers#show_all'

  post 'interviewers/show_all' => 'interviewers#show_all'

  get 'schedules/new/:id' => 'schedules#new', :as => 'schedules/new'

  get 'positions/:id/exams/unassign/:exam_id' => 'positions#unassign', :as => :unassign

  get 'positions/:id/exams/assign/:exam_id' => 'positions#assign', :as => :assign

  controller :applicants do
    con = 'applicants/'
    get con+'show_all' => :show_all
    post con+'show_all' => :show_all, :as => 'show_all'
    post con+':id' => :show
    get 'search_applicant' => :search_applicant
    get con+'header_search' => :header_search
    get 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'
    post 'assign_interviewer/:id' => :assign_interviewer, :as => con+'assign_interviewer'

  	get con+'get_info' => :get_info
  	get con+'get_interviewer' => :get_interviewer
  end

  resources :schedules

  resources :grades

  resources :exams

  resources :interviewers

  resources :positions, :only =>[:index, :create, :update, :destroy, :show]

  resources :applicants

  root :to => "home#index", :as => "index"

end

app/views/layouts/_header.html.erb
<header>
 <nav class="navbar navbar-fixed-top">

      <div class="col-md-2 col-sm-3" id="logo">
        <div class="navbar-brand">
          infoman/AMSS
        </div>
      </div>



      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li id="search">
          <%= form_tag applicants_header_search_path, :method => :get do%>
            <%= text_field_tag :applicant_name ,params[:applicant_name] ,:placeholder=>"Search Applicant", :class=>"input"%>
            <%= submit_tag '&#57347;'.html_safe, :class=> "submit"%>
          <% end %>
        </li>
        <li><%= link_to "Applicants", applicants_path %>             </li>
        <li><%= link_to "Interviewers", interviewers_show_all_path %></li>
        <li><%= link_to "Schedules", schedules_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
          role="button" aria-expanded="false">
            <% if session[:admin_id].nil? %>
              Login
            <% else %>
              <%= Admin.find(session[:admin_id]).name %>
            <% end %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Edit profile", edit_admin_path(session[:admin_id]) %></li>
            <li class="divider"></li>
            <li><%= link_to 'logout',logout_path, :method=>:delete%></li>
          </ul>
        </li>
      </ul>
    </div>


  </nav>
</header>

app/views/layouts/_side.html.erb
<div class="row">
  <div class="col-md-12" id="admin_pic" data-color='red' data-image=<%= "\"/images/#{Admin.find(session[:admin_id]).image_name}\"".html_safe %> >
    <div class="row text-center">
      <span class="text-center">

        <%@image_name = Admin.find(session[:admin_id]).image_name%>

        <% if File.exists?("#{RAILS_ROOT}/public/images/#{@image_name}") %>
          <%= image_tag "#{@image_name}" , :size => "100x100" , :class=>"img-circle" %>
        <% else %>
          <script type="text/javascript">
            $('#admin_pic').attr('data-image', '/images/404.jpg');
          </script>
          <%= image_tag('404.jpg' , :size => "100x100", :class=>"img-circle") %>
        <% end %>

        <h3><%= Admin.find(session[:admin_id]).name%></h3>
        <%= link_to "Edit profile", edit_admin_path(session[:admin_id]) %><br/>
        <%= link_to 'LOGOUT',logout_path, :method=>:delete, :id=>"logout_button"%>
      </span>
    </div>
  </div>



  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">

    <div class="panel panel-success">
      <%= link_to index_path do%>
        <div class="panel-heading" role='tab'>
            <h4 class="panel-title">
              Dashboard
            </h4>
        </div>
      <% end %>
    </div>

    <div class="panel panel-success">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
      href="#applicants" aria-expanded="false" aria-controls="applicants">
        <div class="panel-heading btn-success" role="tab" id="applicant">
          <h4 class="panel-title">
            Applicants
          </h4>
        </div>
      </a>
      <div id="applicants" class="panel-collapse collapse" role="tabpanel"
      aria-labelledby="Applicants">
        <div class="list-group">
          <%= link_to applicants_path do%> <li class="list-group-item"> Manage Applicants</li> <% end %>
          <%= link_to new_applicant_path do%> <li class="list-group-item"> Add new Applicant</li> <% end %>
          <%= link_to applicants_show_all_path do%> <li class="list-group-item"> Show all Applicants</li> <% end %>
          <%= link_to search_applicant_path do%> <li class="list-group-item"> Search Applicant</li> <% end %>
        </div>
      </div>
    </div>

    <div class="panel panel-success">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
      href="#interviewers" aria-expanded="false" aria-controls="interviewers">
        <div class="panel-heading btn-success" role="tab" id="interviewer">
          <h4 class="panel-title">
            Interviewer
          </h4>
        </div>
      </a>
      <div id="interviewers" class="panel-collapse collapse" role="tabpanel"
      aria-labelledby="interviewer">
        <div class="list-group">
          <!-- <%= link_to interviewers_path do%> <li class="list-group-item"> Manage Interviewers</li> <% end %> -->
          <%= link_to new_interviewer_path do%> <li class="list-group-item"> Add New Interviewer</li> <% end %>
          <%= link_to interviewers_show_all_path do%> <li class="list-group-item"> Show all interviewers</li> <% end %>
        </div>
      </div>
    </div>

    <div class="panel panel-success">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
      href="#schedules" aria-expanded="false" aria-controls="schedules">
        <div class="panel-heading btn-success" role="tab" id="schedule">
          <h4 class="panel-title">
            Schedule
          </h4>
        </div>
      </a>
      <div id="schedules" class="panel-collapse collapse" role="tabpanel"
      aria-labelledby="schedule">
        <div class="list-group">
          <%= link_to schedules_path do%> <li class="list-group-item"> Show Schedules</li> <% end %>
          <%= link_to applicant_schedules_path do%> <li class="list-group-item"> Per Applicant</li> <% end %>
          <%= link_to interviewer_schedules_path do%> <li class="list-group-item"> Per Interviewer</li> <% end %>
        </div>
      </div>
    </div>

    <div class="panel panel-success">
      <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
      href="#maintenance_" aria-expanded="false" aria-controls="maintenance_">
        <div class="panel-heading btn-success" role="tab" id="maintenance">
          <h4 class="panel-title">
            Maintenance
          </h4>
        </div>
      </a>
      <div id="maintenance_" class="panel-collapse collapse" role="tabpanel"
      aria-labelledby="maintenance">
        <div class="list-group">
          <%= link_to positions_path do%> <li class="list-group-item"> Positions</li> <% end %>
          <%= link_to schools_path do%> <li class="list-group-item"> Schools</li> <% end %>
          <%= link_to exams_path do%> <li class="list-group-item"> Exams</li> <% end %>
          <%= link_to departments_path do%> <li class="list-group-item"> Departments</li> <% end %>
        </div>
      </div>
    </div>


  </div>
</div>


<%= javascript_include_tag 'blur.js' %>


<script type="text/javascript">

  $(function(){
    var image_name = $('#admin_pic').data('image');
    image_name = "url(\'"+image_name+"\')";
    $('#admin_pic').css('background-image', image_name);
    $('#admin_pic').blurjs({
        source: '#admin_pic',                  //Background to blur
        radius: 20,                            //Blur Radius
        overlay: 'rgba(28,251,50,0.3)',        //Overlay Color, follow CSS3's rgba() syntax
        cache: false,                          //If set to true, blurred image will be cached and used in the future. If image is in cache already, it will be used.
        cacheKeyPrefix: 'blurjs-'
    });
    $('#admin_pic').css('background-position', 'center center');
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>AMSS</title>

  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
  <meta content="ojt project" name="description" />
  <meta content="infomaninc" name="author" />

  <% unless controller.controller_name == 'sessions' &&
  controller.action_name == 'new'%>
  <%= stylesheet_link_tag 'dataTable.css'%>
  <%= stylesheet_link_tag 'date-picker.css'%>
  <%= stylesheet_link_tag 'fullcalendar.css' %>
  <%= stylesheet_link_tag 'fullcalendar.print.css', :media=>'print' %>
  <%= stylesheet_link_tag 'idle.css'%>
  <%= stylesheet_link_tag 'jquery-ui-timepicker-addon.css'%>
  <%= stylesheet_link_tag 'jquery-ui.css'%>
  <%= stylesheet_link_tag 'jquery.circliful.css'%>
  <%= stylesheet_link_tag 'masonry.css'%>
  <%= stylesheet_link_tag 'metro-bootstrap.css'%>
  <%= stylesheet_link_tag 'my.css'%>
  <%= stylesheet_link_tag 'scaffold.css'%>
  <%= stylesheet_link_tag 'smoke.css'%>


  <% end %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

  <%= javascript_include_tag 'moment.js' %>
  <%= javascript_include_tag 'bootstrap.js' %>

  <%= javascript_include_tag 'quantize.js' %>
  <%= javascript_include_tag 'color-thief.js' %>
  <%= javascript_include_tag 'fullcalendar.js' %>
  <%= javascript_include_tag 'idle.js' %>
  <%= javascript_include_tag 'jquery-ui.min.js' %>
  <%= javascript_include_tag 'jquery.dataTables.min.js' %>
  <%= javascript_include_tag 'jquery.dataTablesExt.fnSetFilteringDelay.js' %>
  <%= javascript_include_tag 'jquery.foggy.min.js' %>
  <%= javascript_include_tag 'jquery-ui-timepicker-addon.js' %>
  <%= javascript_include_tag 'jquery.circliful.min.js' %>
  <%= javascript_include_tag 'masonry.pkgd.min.js' %>
  <%= javascript_include_tag 'smoke.min.js' %>
  <%= javascript_include_tag 'highcharts', 'chartkick' %>
  <%# javascript_include_tag 'jquery.tablesorter.js' %>
  <%# javascript_include_tag 'jquery.tablesorter.widgets.js' %>
</head>

<body>

<div class = "container-fluid">

<% if controller.controller_name == 'sessions' &&
  controller.action_name == 'new'%>
  <%= yield %>
<% else %>
  <div class="row">
    <%= render 'layouts/header' %>
  </div>

  <div class="row" id="bodyContent">
    <div class="col-md-2 col-sm-3 col-lg-2" id="side">

      <%= render 'layouts/side' %>
    </div>

    <div class="col-md-10 col-sm-9 col-lg-10" id="body">
       <%= yield %>
    </div>
  </div>
<% end %>
</div>

<div id="data"></div>
</body>


<%if @admin %>
  <div id="backdrop" class="idleBack">
    <div class="jumbotron vertical-center">
      <div class="container">
      <h1> Hey <%= @admin.name %>, </h1>
      <p> It seems that you've been away for a long time. We just want to inform you that you will be logged-out after
          some minutes. Just make some action to get back.
      </p>
      </div>
    </div>
  </div>
<% end %>

<% unless controller.controller_name == 'sessions' &&
  controller.action_name == 'new'%>

  <script type="text/javascript">
  $('document').ready(function() {
    setIdleTimeout(1800000); //1800000 30mins
    setAwayTimeout(3600000); //36000000 1hour
    var count = 0;

    document.onIdle=function(){
          // $('body').foggy({
          //   blurRadius: 2,
          //   opacity: 0.8,
          //   cssFilterSupport: true
          // });
        console.log('idle');
        $('#backdrop').switchClass( "idleBack", "idle", 3000, "easeInOutQuad" );
      }
    document.onAway=function(){
      $.ajax({
        url: "/logout",
        method: 'delete',
        type: 'post',
        success: function(result) {
          location.href= '/'
        }
      })
    }

    document.onBack=function(a,b){
      if(a){
        $('#backdrop').switchClass( "idle", "idleBack", 3000, "easeInOutQuad" );
        // $('body').foggy(false)
      }
      if(b){

      }
    }
  });
  </script>
<% end %>
</html>

<!--
setAwayTimeout(4000);
document.onIdle=function(){
  $("#div_idle").css("opacity","1")};
document.onAway=function();
  $("#div_away").css("opacity","1")};
document.onBack=function(a,b);
  if(a);
  $("#div_idle").css("opacity","0.2")}if(b);
  $("#div_away").css("opacity","0.2")}};
 -->
<script type="text/javascript">


  $.smkProgressBar({
    element: '#bodyContent',
    status: 'start'
  });

$(document).ready(function(){
  setTimeout(function() {
    $.smkProgressBar({
      element: '#bodyContent',
      status: 'end'
    });
  }, 1000);
});
</script>

app/views/layouts/pdf.html.erb
<%= yield %>

app/views/layouts/wizard.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>AMSS</title>

  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
  <meta content="ojt project" name="description" />
  <meta content="infomaninc" name="author" />
  <%= stylesheet_link_tag 'metro-bootstrap.css'%>
  <%= stylesheet_link_tag 'wizard.css'%>
  <%= stylesheet_link_tag 'smoke.css'%>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

  <%= javascript_include_tag 'bootstrap.js' %>
  <%= javascript_include_tag 'jquery.spectrum.js' %>
  <%= javascript_include_tag 'smoke.min.js' %>


</head>

<body>

<div class = "container-fluid">
  <%= yield %>
</html>